GitNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Security;
using GitNet.DB.Repository;
using GitNet.Utilities;
using AutoMapper;

namespace Controllers
{
	[HandleError]
	public class HomeController : Controller
	{
		public ActionResult Index ()
		{
			ViewBag.Message = "Welcome to ASP.NET MVC on Mono!";
			return View ();
		}
		
		[Authorize]
		public ActionResult About()
		{
			return View ();
		}
		
		[Authorize]
		public ActionResult Dashboard()
		{
			ViewBag.Repositories = new RepositoryRepository(this.DBContext()).GetAll(User.Identity.Name);
            ViewBag.Projects = new ProjectRepository(this.DBContext()).GetAll(User.Identity.Name);
			return View();	
		}
	}
}

GitNet/Controllers/RepositoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Security;
using GitNet.Models;
using Automation = GitNet.GitClient.RepositoryAutomation;
using AutoMapper;

namespace Controllers
{
	public class RepositoryController : Controller
	{
		
		[Authorize]
		public ActionResult New() {
			return View ();	
		}
		
		[Authorize]
		[HttpPost]
		public ActionResult New(GitNet.DB.Repo repository) {
            var session = GitNet.DB.Repository.NHibernateHelper.OpenSession();
			var repositoryRepository = new GitNet.DB.Repository.RepositoryRepository(session);
			
			var username = Membership.GetUser().UserName;
            repository.Owner = username;
            var modelRepo = Mapper.Map<GitNet.DB.Repo>(repository);

			try {
                repositoryRepository.Add(modelRepo);
                Automation.CreateRepository(modelRepo.UrlName);
			} catch {
				Automation.DeleteRepository(modelRepo.UrlName);
                if (session.Contains(modelRepo)) {
                    session.Delete(modelRepo);
                       session.Flush();
                }
				throw;
			}
            return RedirectToRoute("GitRepositoryBrowser", new {username = "", reponame = modelRepo.UrlName});
		}
	}
}

GitNet/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<section>
	<p>This product incorporates the following projects</p>
	<section>
		<h1>JGit</h1>
		<p>Licensed under the Eclipse Distribution License</p>
	</section>
	<section>
		<h1>IKVM</h1>
		<p>Licensed under the IKVM license http://sourceforge.net/apps/mediawiki/ikvm/index.php?title=License</p>
		<section>
			<h1>OpenJDK</h1>
			<p>Licensed under the GNU GPL + ClassPath exception</p>
		</section>
	</section>
	<section>
		<h1>Automapper</h1>
		<p>Licensed under the Automapper license https://github.com/AutoMapper/AutoMapper/blob/master/LICENSE.txt</p>
	</section>
	<section>
		<h1>NHibernate</h1>
		<p>Licensed under the LGPL v2.1</p>
	</section>
	<section>
		<h1>ASP.NET MVC 3</h1>
		<p>Licensed under the Microsoft Public License</p>
	</section>
</section>

GitNet/Views/Home/Dashboard.cshtml
@using System.Linq;
@{
    ViewBag.Title = "Dashboard";
}

<section class="dashboard-list">
	<div class="list-header">
		@Html.ActionLink("Create", "New", "Repository")
		<h1>Repositories</h1>
	</div>
		
	@if (ViewBag.Repositories.Count > 0) {
	<ul class="Repositories">
		@foreach (var repository in ViewBag.Repositories) {
			<li>@Html.RouteLink((string)repository.Name, "GitRepositoryBrowser", new {username = "", reponame = repository.UrlName})</li>
		}
	</ul>
	} else {
		<p>No repositories yet, why don't you @Html.ActionLink("add one", "New", "Repository"), or fork someone else's?</p>
	}
</section>

<section class="dashboard-list">
	<div class="list-header">
		@Html.ActionLink("Create", "New", "Project")
		<h1>Projects</h1>
	</div>
	
	@if (ViewBag.Projects.Count > 0) {
		<ul class="projects">
			@foreach (var project in ViewBag.Projects) {
				<li>@Html.RouteLink((string)project.Name, "Project", new {username = "", identifier = project.UrlName})</li>
			}
		</ul>
	} else {
		<p>You have no projects, why don't you @Html.ActionLink("create one", "New", "Project")?</p>
	}
</section>

<section class="dashboard-list">
	<div class="list-header">
		<h1>Assigned Issues</h1>
	</div>
	
	<p>You have no open issues, hooray!</p>
</section>

<br class="clear"/>

GitNet/Views/Home/Index.cshtml
<div>
	@ViewBag.Message
</div>

<p> Your roles: @ViewBag.Roles </p>